### ISSUE TITLE
No example nor processor board that works

### ISSUE THREAD

**Issue by ajsb85** [sparkfun/MicroMod_Asset_Tracker#6]
Hi, I try all the processor boards and all the examples.

And no one works.

Seems the **nRF5280 Processor** is the perfect for this carrier board, but is broken the Arduino file when you install the board.

https://github.com/sparkfun/MicroMod_Processor_Board-nRF52840/issues/3

Cheers.

**Comment by PaulZC** [comment]
Hi Alexander (@ajsb85 ),

They do work - trust me - I've been using them today.

For the nRF52840, there are some extra steps to create the SparkFun MicroMod nRF52840 Processor Board. Follow the instructions here:

https://learn.sparkfun.com/tutorials/micromod-nrf52840-processor-hookup-guide/arduino-software-setup

Then select the correct Board:

![image](https://user-images.githubusercontent.com/5690545/162789930-52debf12-c544-4568-9419-88a6eb019b02.png)

If you are still having problems, please upload a copy of any error messages you are seeing.

Best wishes,
Paul

**Comment by PaulZC** [comment]
Hi Alexander (@ajsb85 ),

Were you able to get the nRF52840 Processor Board working?

Best wishes,
Paul

**Comment by ajsb85** [comment]
No. 
And I read the forum posts and nothing works.
The board base from Arduino was updated and not the files provided by SparkFun.
If you can tell me which version of the Arduino boards works I can downgrade it...

**Comment by PaulZC** [comment]
Hello Alexander,

I followed the instructions in the hook-up guide - but it was a few months ago. I am using "Arduino Mbed OS Boards" Version 1.3.1 DEPRECATED:

![image](https://user-images.githubusercontent.com/5690545/164535228-af9e9a88-855d-4ee8-9c57-68fc07044cee.png)

![image](https://user-images.githubusercontent.com/5690545/164534975-7f55a793-fba1-49d9-8b04-cfe4f676484a.png)


But I see that the repository has been updated so that it should work with the newer "Arduino Mbed OS Nano Boards" Version 3.0.1:

![image](https://user-images.githubusercontent.com/5690545/164536874-f489998b-4018-4f96-a017-2928b9b96632.png)


Please try "Arduino Mbed OS Nano Boards" Version 3.0.1 - using the link in the hook-up guide:

![image](https://user-images.githubusercontent.com/5690545/164537104-5ef081e4-3e1e-4eef-af05-c26c3f3c7654.png)

https://github.com/sparkfun/MicroMod_Processor_Board-nRF52840/archive/master.zip


If you still have problems, please try "Arduino Mbed OS Boards" Version 1.3.1 DEPRECATED - and use the link below to download an older version of the SF_MM_nRF52840_PB files. This is the same one I am using.

https://github.com/sparkfun/MicroMod_Processor_Board-nRF52840/archive/4bddb83c139195fad9654aa633374239504ced05.zip

If, after this, you are still having problems, please provide more information:

Do you see any errors in the Arduino IDE when compiling and uploading the code?

What do you see in the Serial Monitor when the code is running?

How do you have the board connected?

Which LEDs are lit up on the board?

Have you tried the simplest "AssetTracker_Example1_Blink"? Does the LED on the processor board blink?

Thank you,
Paul

**Comment by ajsb85** [comment]
Dear @PaulZC .

I tried both versions of the DEPRECATED board 3.0.1 and 1.3.1 and I got the same error for both in the process of the uploading.

```
An error occurred while uploading the sketch
SAM-BA operation failed****
```

**Comment by ajsb85** [comment]
It's working. (1.3.1)
I really appreciate it.

**Comment by PaulZC** [comment]
Closing... Please re-open if you need more help with this.
Best,
Paul
